### PR TITLE
ReSpec build script

### PR DESCRIPTION
**Pull request by ralfhandl**
- [x] EDITORS.md with guessed lists of current and previous editors
- [x] package.json with dependencies
- [x] scripts/md2html/* build script adjusted from OAS

Preview:
* https://ralfhandl.github.io/OpenAPI-Specification/overlay/v1.0.0.html

### CODE REVIEW

**Comment by handrews** [comment]
@ralfhandl I don't think I've ever made a single contribution to the Overlays spec, so I should not be on the 1.0 editors list.

**Comment by lornajane** [comment]
Can this be used locally? Let's add the instructions in to the contributing file.

I would name all those editors as current editors, both Ron and Darrel did a LOT to get Overlays to this first 1.0 release.

**Comment by ralfhandl** [comment]
Added CONTRIBUTING.md with local build instructions

**Review by lornajane — APPROVED** [review]
Thank you! I added some words to the Contributing file while I was reviewing.

**Pull request merged**
